version: "3.9"

services:
  db_sandbox:
    image: postgres:latest
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: 
      POSTGRES_PASSWORD: 
  db_admin:
    image: dpage/pgadmin4
    ports:
      - "82:80"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 
      PGADMIN_DEFAULT_PASSWORD: 