name: ES Lint

on:
  pull_request:
    branches: [main]
<<<<<<< HEAD
    branches: [containerize-React] #Remove before merge main
=======
    branches: [main] #Remove before merge main
>>>>>>> 0b51ce03bc6fef7245a2a8d7d8bbc8ed4964842c

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: |
          cd backend
          npm init @eslint/config
      - name: Install typescript and eslint
        run: npm install --save-dev @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint-config-react-app eslint@^8.0.0 typescript
      - name: Lint it
        run: npx eslint .